# Generated by Django 4.2.3 on 2024-03-31 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('araclar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekspertiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(null=True, upload_to='araclar/', verbose_name='Ekpertiz Fotografı')),
                ('arkaBagajKapagi', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('solArkaCamurluk', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('sagArkaKapi', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('sagOnKapi', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('tavan', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('solArkaKapi', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('solOnKapi', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('sagOnCamurluk', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('motorKaputu', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('motorHacmi', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('solOnCamurluk', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('onTampon', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('arkaTampon', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('sagMarspiyel', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('solMarspiyel', models.CharField(choices=[('boyali', 'Boyalı'), ('degisen', 'Değişen'), ('orijinal', 'Orijinal')], max_length=50)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='araclar.araclar')),
            ],
        ),
    ]
