# Generated by Django 4.2.3 on 2024-03-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araclar', '0004_donanım'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donanım',
            name='dişDonanim1',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='dişDonanim2',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='dişDonanim3',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='dişDonanim4',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='dişDonanim5',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='dişDonanim6',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='güvenlik1',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='güvenlik2',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='güvenlik3',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='güvenlik4',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='güvenlik5',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='güvenlik6',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='içDonanim1',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='içDonanim2',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='içDonanim3',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='içDonanim4',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='içDonanim5',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donanım',
            name='içDonanim6',
            field=models.CharField(blank=True, choices=[('Aktif Ön Koltuk Başlıkları', 'Aktif Ön Koltuk Başlıkları'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Yükseklik Ayarlı Ön Emniyet Kemerleri', 'Yükseklik Ayarlı Ön Emniyet Kemerleri'), ('Merkezi Kilit', 'Merkezi Kilit'), ('Ayarlanabilir Direksiyon', 'Ayarlanabilir Direksiyon'), ('Elektrikli Ön Camlar', 'Elektrikli Ön Camlar'), ('Fonksiyonel Direksiyon', 'Fonksiyonel Direksiyon'), ('Hidrolik Direksiyon', 'Hidrolik Direksiyon'), ('Yol Bilgisayarı', 'Yol Bilgisayarı'), ('Klima (Analog)', 'Klima (Analog)'), ('Sunroof', 'Sunroof'), ('Arka Cam Buz Çözücü', 'Arka Cam Buz Çözücü')], max_length=50, null=True),
        ),
    ]
