# Generated by Django 4.2.3 on 2024-04-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('araclar', '0005_alter_donanım_dişdonanim1_alter_donanım_dişdonanim2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donanım',
            name='arac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donanimlar', to='araclar.araclar'),
        ),
    ]
